# Generated by Django 4.0.6 on 2022-07-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=250)),
                ('start_date_of_reg', models.DateField()),
                ('last_date_of_reg', models.DateField()),
                ('tournament_start_date', models.DateField()),
                ('tournament_end_date', models.DateField()),
                ('tournament_time', models.DateTimeField()),
                ('max_score_per_set', models.PositiveIntegerField()),
                ('total_players', models.PositiveIntegerField()),
                ('tournament_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=50)),
                ('match_type', models.CharField(choices=[("men's single", "Men's Single"), ("women's single", "Women's Single"), ("men's double", "Men's Double"), ("women's double", "Women's Double"), ('double', 'Double')], default="men's single", max_length=50)),
            ],
        ),
    ]
