# Generated by Django 4.0.6 on 2022-07-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_date_of_reg',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_time',
            field=models.TimeField(),
        ),
    ]
