# Generated by Django 4.0.6 on 2022-07-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=250)),
                ('start_date_of_reg', models.DateTimeField()),
                ('last_date_of_reg', models.DateTimeField()),
                ('tournament_start_date', models.DateTimeField()),
                ('tournament_end_date', models.DateTimeField()),
                ('tournament_time', models.DateTimeField()),
                ('max_score_per_set', models.IntegerField()),
                ('total_players', models.IntegerField()),
                ('tournament_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=50)),
                ('match_type', models.CharField(choices=[("men's single", "Men's Single"), ("women's single", "Women's Single"), ("men's double", "Men's Double"), ("women's double", "Women's Double"), ('double', 'Double')], default="men's single", max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tournament_reg_rel',
            name='is_accepted',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('not accepted', 'Not Accepted')], default='accepted', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament_reg_rel',
            name='tournament',
            field=models.ManyToManyField(to='tournament.tournament'),
        ),
    ]
