# Generated by Django 4.0.6 on 2022-07-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_tournament_start_date_of_reg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='last_date_of_reg',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date_of_reg',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_start_date',
            field=models.DateTimeField(),
        ),
    ]
