# Generated by Django 4.0.6 on 2022-07-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_tournament_reg_rel_is_accepted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament_reg_rel',
        ),
    ]
