# Generated by Django 4.0.6 on 2022-07-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('tournament', '0003_delete_tournament_reg_rel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament_reg_rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.CharField(choices=[('accepted', 'Accepted'), ('not accepted', 'Not Accepted')], default='accepted', max_length=50)),
                ('user', models.ManyToManyField(to='user_auth.profile')),
            ],
        ),
    ]
