# Generated by Django 4.0.6 on 2022-07-19 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_info', '0006_remove_customuser_tournament_and_more'),
        ('tournament', '0004_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tournament_profile_rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.CharField(choices=[('accepted', 'Accepted'), ('not accepted', 'Not Accepted'), ('denied', 'Denied')], default='accepted', max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='user',
            field=models.ManyToManyField(through='tournament.tournament_profile_rel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament_profile_rel',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
    ]
