# Generated by Django 4.0.6 on 2022-07-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('tournament', '0005_remove_tournament_reg_rel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_reg_rel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_auth.profile'),
        ),
    ]
