# Generated by Django 4.0.6 on 2022-07-19 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0005_tournament_profile_rel_tournament_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='date_sent',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='tournament_id',
        ),
        migrations.AddField(
            model_name='invitation',
            name='from_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Form_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='To_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
