# Generated by Django 4.0.6 on 2022-07-19 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0006_remove_invitation_date_sent_remove_invitation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[(0, 'Accepted'), (1, 'Not_Accepted'), (2, 'Pending')], default=2, max_length=20),
        ),
        migrations.AddField(
            model_name='invitation',
            name='tournament_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Invitation', to='tournament.tournament'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
