# Generated by Django 4.0.6 on 2022-07-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_reg_rel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_reg_rel',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.tournament'),
        ),
    ]
