# Generated by Django 4.0.6 on 2022-07-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('tournament', '0007_tournament_reg_rel_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.tournament')),
                ('tournament_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_auth.profile')),
            ],
        ),
    ]
