# Generated by Django 4.0.6 on 2022-07-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_invitation_status_invitation_tournament_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='user_id',
        ),
    ]
