# Generated by Django 4.0.6 on 2022-07-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('tournament', '0008_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='last_date_of_reg',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_score_per_set',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date_of_reg',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='total_players',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_start_date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='tournament_reg_rel',
            name='tournament',
        ),
        migrations.AddField(
            model_name='tournament_reg_rel',
            name='tournament',
            field=models.ManyToManyField(null=True, to='tournament.tournament'),
        ),
        migrations.RemoveField(
            model_name='tournament_reg_rel',
            name='user',
        ),
        migrations.AddField(
            model_name='tournament_reg_rel',
            name='user',
            field=models.ManyToManyField(null=True, to='user_auth.profile'),
        ),
        migrations.RemoveField(
            model_name='winner',
            name='tournament',
        ),
        migrations.AddField(
            model_name='winner',
            name='tournament',
            field=models.ManyToManyField(null=True, to='tournament.tournament'),
        ),
        migrations.RemoveField(
            model_name='winner',
            name='tournament_winner',
        ),
        migrations.AddField(
            model_name='winner',
            name='tournament_winner',
            field=models.ManyToManyField(null=True, to='user_auth.profile'),
        ),
    ]
