# Generated by Django 4.0.6 on 2022-07-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('tournament', '0009_alter_tournament_last_date_of_reg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament_reg_rel',
            name='tournament',
            field=models.ManyToManyField(to='tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='tournament_reg_rel',
            name='user',
            field=models.ManyToManyField(to='user_auth.profile'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='tournament',
            field=models.ManyToManyField(to='tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='tournament_winner',
            field=models.ManyToManyField(to='user_auth.profile'),
        ),
    ]
