# Generated by Django 4.0.6 on 2022-07-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Leave Blank', max_length=40, unique=True)),
                ('email_id', models.EmailField(max_length=300, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')])),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='images')),
                ('match_played', models.IntegerField()),
                ('match_won', models.IntegerField()),
                ('played_tournament_name', models.CharField(max_length=200)),
                ('tournament_won', models.CharField(max_length=200)),
                ('is_player', models.BooleanField()),
            ],
        ),
    ]
