# Generated by Django 4.0.6 on 2022-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_id',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
