# Generated by Django 4.0.6 on 2022-07-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_remove_winner_tournament_and_more'),
        ('user_auth', '0002_alter_profile_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tournament_profile_rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.CharField(choices=[('accepted', 'Accepted'), ('not accepted', 'Not Accepted')], default='accepted', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='tournament',
            field=models.ManyToManyField(through='user_auth.tournament_profile_rel', to='tournament.tournament'),
        ),
        migrations.AddField(
            model_name='tournament_profile_rel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.profile'),
        ),
        migrations.AddField(
            model_name='tournament_profile_rel',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
    ]
