# Generated by Django 4.0.6 on 2022-07-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('match_round', models.CharField(choices=[('round_1', 'Round 1'), ('round_2', 'SemiFinal'), ('round_3', 'Final')], default='round_1', max_length=50)),
                ('player_id_home', models.CharField(max_length=200)),
                ('player_id_away', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Set_Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_no', models.IntegerField()),
                ('player_id_home_score', models.IntegerField()),
                ('player_id_away_score', models.IntegerField()),
            ],
        ),
    ]
