# Generated by Django 4.0.6 on 2022-07-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament_profile_rel',
            name='is_accepted',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('not accepted', 'Not Accepted'), ('denied', 'Denied')], default='accepted', max_length=50),
        ),
    ]
