# Generated by Django 4.0.6 on 2022-07-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_alter_tournament_profile_rel_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tournament_won',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
