# Generated by Django 4.0.6 on 2022-07-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_invitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
