# Generated by Django 4.0.6 on 2022-07-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_delete_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='tournament_profile_rel',
        ),
    ]
