# Generated by Django 4.0.6 on 2022-07-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0008_alter_customuser_gender_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[('male', 'male'), ('female', 'female'), ('not specified', 'not specified')], default='not specified'),
        ),
    ]
