# Generated by Django 4.0.6 on 2022-07-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0010_alter_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
    ]
