# Generated by Django 4.0.6 on 2022-07-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0011_remove_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='match_played',
            field=models.IntegerField(default=0),
        ),
    ]
