# Generated by Django 4.0.6 on 2022-07-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0012_alter_customuser_match_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='match_won',
            field=models.IntegerField(default=0),
        ),
    ]
