# Generated by Django 4.0.6 on 2022-07-12 11:10

from django.db import migrations, models
import django.forms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0013_customuser_age_alter_customuser_match_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_player',
            field=models.BooleanField(verbose_name=django.forms.fields.NullBooleanField),
        ),
    ]
