# Generated by Django 4.0.6 on 2022-07-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tournament', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user_info', '0016_rename_customuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
