# Generated by Django 4.0.6 on 2022-07-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0019_rename_user_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='played_tournament_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tournament_won',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
