# Generated by Django 4.0.6 on 2022-07-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0020_alter_customuser_age_alter_customuser_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
